### ISSUE TITLE
I am getting error, can you plz help me resolve this error 

### ISSUE THREAD

**Issue by rutvikvasoya** [daedalus-tech/mc-mot#5]
Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients, 48.9 GFLOPs
Adding AutoShape... 
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
/home/webclues/mc-mot-main/main.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  det[:, :4] = np.int0(det[:, :4])
Traceback (most recent call last):
  File "/home/webclues/mc-mot-main/main.py", line 127, in <module>
    main(opts)
  File "/home/webclues/mc-mot-main/main.py", line 71, in main
    frames[i] = utilities.draw_tracks(
  File "/home/webclues/mc-mot-main/utilities.py", line 111, in draw_tracks
    labels = tracks[:, 5]
IndexError: index 5 is out of bounds for axis 1 with size 5

**Comment by nisshakny** [comment]
Hi! I am having the same problem, any solutions?

**Comment by b2210765027** [comment]
Same problem... Any solutions?
